services:
  bun:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    container_name: bookshop-be
    restart: always
    env_file: .env
    command: >
      bash -c "if [[ '$SETUP' == 'true' ]]; then 
        bun migrate && 
        bun seed;
      fi;
      bun src/app.ts;"
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/opt/bookshop-be/src
